version: '3'
services:
  cuda-vector-add-all:
    image: nvidia/cuda:12.2.0-devel-ubuntu22.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2']
              capabilities: [gpu]
