version: '3'
services:
  pytorch:
    build:
      context: .
      network: host
    image: test:latest
    command: tail -F anything
    ulimits:
      rtprio: 95
      memlock: -1
      stack: 67108864
    ipc: host
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2']
              capabilities: [gpu]
